- name: Update apt cache
  tags:
  - update
  apt:
    update_cache: yes

- name: Upgrade system
  tags:
  - upgrade
  apt:
    upgrade: dist

- name: Set the stable docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} edge"
    state: present
    update_cache: yes

- name: Install Docker
  package:
    name: docker-ce
    allow_unauthenticated: yes
    state: present

