aws:
  vars:
    ansible_ssh_user: "ubuntu"
    ansible_python_interpreter: /usr/bin/python3
    ansible_become: yes
  children:
    testinstances:
      hosts:
        testsuperpeer1.rightmesh.io:
          ansible_host: 34.221.96.239
          ansible_ssh_private_key_file: ~/.ssh/testsuperpeer1rightmeshio.pem
        testsuperpeer2.rightmesh.io:
          ansible_host: 54.214.208.224
          ansible_ssh_private_key_file: ~/.ssh/testsuperpeer2rightmeshio.pem
        testsuperpeer3.rightmesh.io:
          ansible_host: 34.219.123.140
          ansible_ssh_private_key_file: ~/.ssh/testsuperpeer3rightmeshio.pem

# For local testing
localvm:
  vars:
    ansible_ssh_user: "vagrant"
    ansible_ssh_private_key_file: '.vagrant/machines/default/virtualbox/private_key'
    ansible_port: 2222
    ansible_python_interpreter: /usr/bin/python3
    ansible_become: yes
    domain_name: localhost
  hosts:
    localhost:
      ansible_host: 127.0.0.1
