aws:
  vars:
    ansible_ssh_user: "ubuntu"
    ansible_python_interpreter: /usr/bin/python3
    ansible_become: yes
  children:
    superpeer:
      vars:
        domain_name: superpeer1.rightmesh.io
# Uncomment when we want to deploy
#    viz-superpeer:
#      vars:
#        domain_name: <viz domain name here>
