- hosts: localhost
  tasks:
  - name: Build Superpeer image
    docker_image:
      path: ./docker/superPeer
      name: superpeer
      tag: 0.1

  - name: Build Parity image
    docker_image:
      path: ./docker/parity
      name: parity
      tag: 0.1

  - name: Create SuperPeer container
    docker_container:
      name: superpeer
      image: superpeer:0.1