- hosts: all
  roles: [ 'base' ]
  tasks:

  - name: Copy pre-built Docker images to remote
    copy:
      src: docker/images
      dest: ~/build

  - name: Check SuperPeer image exists
    stat:
      path: ~/build/docker/images/superPeer.tar
    register: image
  - debug:
      msg: "Image file exists"
    when: image.stat.exists is defined