# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.hostname = "superpeer-vm"

  config.vm.network "forwarded_port", guest: 40000, host: 40000
  config.vm.network "private_network", :type => 'dhcp', :adapter => 2

  config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = false

     # Customize the amount of memory on the VM:
     vb.memory = "1024" # MB
  end
end
